name: cron_create_release

on:
  workflow_dispatch:
  schedule:
    # AM 03:49 JST 火,水,木,金  (18:49 UTC 月,火,水,木) 
    - cron:  '49 18 * * 1,2,3,4' 
jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v3
      - name: create New TagName
        id: create_new_tagname
        run: |
          #バージョン番号作成

          #最終リリースバージョンのタグ名取得
          LATEST_VERSION=`gh release list --repo $GITHUB_REPOSITORY | head -n 1 | awk '{ print $3 }'`

          #バージョン形式チェック
          regex='v[0-9]+\.[0-9]+\.[0-9]+-[0-9]{8}-[0-9]{2}'
          if [[ ! $LATEST_VERSION =~ $regex ]] ;
          then
            echo "Cannot get latest releaseTag. LATEST_VERSION = $LATEST_VERSION"
            exit 1
          fi

          #git diffのためタグ情報取得
          git fetch --depth 1 origin tag $LATEST_VERSION

          #バージョン番号作成
          MAJOR_VERSION=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $1}'`
          MINOR_VERSION=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $2}'`
          PATCH_VERSION=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $3}'`
          VERSION_DATE=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $4}'`
          VERSION_DATE_COUNT=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $5}'`
          CURRENT_DATE=`date '+%Y%m%d'`

          echo $LATEST_VERSION
          echo $MAJOR_VERSION
          echo $MINOR_VERSION
          echo $PATCH_VERSION
          echo $VERSION_DATE
          echo $VERSION_DATE_COUNT
          echo $CURRENT_DATE

          NEW_TAG=`git diff --name-status $LATEST_VERSION origin/develop -w --ignore-blank-lines | \
          awk -v v1=$MAJOR_VERSION -v v2=$MINOR_VERSION -v v3=$PATCH_VERSION -v v4=$VERSION_DATE -v v5=$VERSION_DATE_COUNT -v datestr=$CURRENT_DATE \
          'BEGIN {
              ap=0;
              db=0;
          }
          {
              # git diffの数だけ繰り返し
              if($1=="A" || $1=="M" || $1=="D"){
                  # 追加・更新・削除があれば
                  if($2~/Program\/Sources\/AP/){
                      # Program/Sources/AP配下のファイルに変更があれば、PATCH_VERSIONを上げる
                      ap++
                  }else if($2~/Program\/Sources\/DB/){
                      # Program/Sources/DB配下のファイルに変更があれば、MINOR_VERSIONを上げる
                      db++
                  }
              }
          }
          END {
              if(db!=0){
                  # MINOR_VERSIONを上げる
                  v2++;
                  v3=0;
              }else if(ap!=0){
                  # PATCH_VERSIONを上げる
                  v3++;
              }

              if(v4==datestr){
                  # 同一日付バージョンが存在する場合
                  v5++
              }else {
                v4=datestr
                v5=1
              }
              printf "v%d.%d.%d-%s-%02d\n",v1,v2,v3,v4,v5
          }'`

          echo $NEW_TAG
          echo "latesttag=$LATEST_VERSION" >> "$GITHUB_OUTPUT"
          echo "newtag=$NEW_TAG" >> "$GITHUB_OUTPUT"

      - name: create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
        run: |
          TAG=${{ steps.create_new_tagname.outputs.newtag }}

          #金曜の場合はlatest release,それ以外の場合はpre releaseとする。
          if [ `date +"%w"` == 5 ]; then
            gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$TAG" \
              --generate-notes
          else
            gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$TAG" \
              --generate-notes \
              --prerelease
          fi

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.create_new_tagname.outputs.newtag }}

      - name: Zip DB Folder
        run: (cd Program/Sources; zip -r ../../Program_Sources_DB.zip ./DB)

      - name: Upload DB Folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ steps.create_new_tagname.outputs.newtag }}
          gh release upload "$TAG" Program_Sources_DB.zip

      - name: Zip & Upload  Patch Folder
        run: |
          LATEST_TAG=${{ steps.create_new_tagname.outputs.latesttag }}
          TAG=${{ steps.create_new_tagname.outputs.newtag }}
          #diff取得
          IFS=$'\n' read -r -d '' -a patch_diff_list < <( git diff $LATEST_TAG $TAG --name-status -w --ignore-blank-lines --relative Program/Sources/DB/Patch && printf '\0' )

          #patch dir取得
          declare -A uniq_patch_dir

          for diff in "${patch_diff_list[@]}"; do
              uniq_patch_dir[`echo $diff | sed -r "s/.*Patch\/(.+)\/.+/\1/g"`]=0 # assigning a placeholder
          done
          echo "patch dir name: ${!uniq_patch_dir[@]}"

          #zip化、Upload
          for patch_dir in "${!uniq_patch_dir[@]}"; do
              (cd Program/Sources/DB/Patch; zip -r ../../../../$patch_dir.zip ./$patch_dir)
              gh release upload "$TAG" $patch_dir.zip
          done
