name: cron_create_release

on: [ workflow_dispatch ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: create New TagName
        id: create_new_tagname
        run: |
          #バージョン番号作成
          LATEST_VERSION=`gh release list | head -n 1 | awk '{ print $3 }'`

          #バージョン形式チェック
          regex='v[0-9]+\.[0-9]+\.[0-9]+-[0-9]{8}-[0-9]{2}'
          if [[ ! $LATEST_VERSION =~ $regex ]] ;
          then
            echo "Cannot get latest releaseTag. LATEST_VERSION = $LATEST_VERSION"
            exit 1
          fi

          #バージョン番号作成
          MAJOR_VERSION=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $1}'`
          MINOR_VERSION=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $2}'`
          PATCH_VERSION=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $3}'`
          VERSION_DATE=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $4}'`
          VERSION_DATE_COUNT=`echo $LATEST_VERSION | awk '{print substr($0, 2)}' | awk -F '[.-]' '{print $5}'`
          CURRENT_DATE=`date '+%Y%m%d'`

          echo $LATEST_VERSION
          echo $MAJOR_VERSION
          echo $MINOR_VERSION
          echo $PATCH_VERSION
          echo $VERSION_DATE
          echo $VERSION_DATE_COUNT
          echo $CURRENT_DATE

          NEW_TAG=`git diff --name-status $LATEST_VERSION origin/develop -w --ignore-blank-lines | \
          awk -v v1=$MAJOR_VERSION -v v2=$MINOR_VERSION -v v3=$PATCH_VERSION -v v4=$VERSION_DATE -v v5=$VERSION_DATE_COUNT -v datestr=$CURRENT_DATE \
          'BEGIN {
              ap=0;
              db=0;
          }
          {
              # git diffの数だけ繰り返し
              if($1=="A" || $1=="M" || $1=="D"){
                  # 追加・更新・削除があれば
                  if($2~/Program\/Source\/AP/){
                      # Program/Source/AP配下のファイルに変更があれば、PATCH_VERSIONを上げる
                      ap++
                  }else if($2~/Program\/Source\/DB/){
                      # Program/Source/DB配下のファイルに変更があれば、MINOR_VERSIONを上げる
                      db++
                  }
              }
          }
          END {
              if(db!=0){
                  # MINOR_VERSIONを上げる
                  v2++;
                  v3=0;
              }else if(ap!=0){
                  # PATCH_VERSIONを上げる
                  v3++;
              }

              if(v4=datestr){
                  # 同一日付バージョンが存在する場合
                  v5++
              }else {
                v4=datestr
                v5=1
              }
              printf "v%d.%d.%d-%s-%02d\n",v1,v2,v3,v4,v5
          }'`

          echo $NEW_TAG
          echo "newtag=$NEW_TAG" >> "$GITHUB_OUTPUT"
